version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./front/.env
  #   volumes:
  #     - ./front/src:/src/src
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./django_backend
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./django_backend/:/usr/src/django_backend/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=moneyApp
    ports:
      - 5432:5432

volumes:
  postgres_data: